### ISSUE TITLE
Pull all playlists instead of just the first page

### ISSUE THREAD

**Issue by alexanderpepper** [alexanderpepper/spotify-utils#2]
The max limit per page of playlists is 50. We need to pull all playlists.

API reference for offset: https://developer.spotify.com/web-api/get-list-users-playlists/

Logic is in `getPlaylists()` method of `spotify-service.js`.

Going to need some kind of Promise API fancy footwork to continually pull and update offset.

Call to get user playlists returns a total, we can simply divide the limit by the offset to know how many times to pull. There's also a `next` property; we can check for that being null to know when we're done. 

I think I prefer using offset / limit to get the number of times to pull.

**Comment by macacollins** [comment]
We should also consider switching to /me/get-playlists instead of /{user-id}/get-playlists

**Comment by alexanderpepper** [comment]
I had that thought too. But that would also entail switching to using the REST API directly, rather than through the spotify-web-api-node package.

**Comment by alexanderpepper** [comment]
Created #10 in reference to @macacollins comment

**Comment by rajatm29** [comment]
https://github.com/kaaes/spotify-web-api-android/issues/105

**Comment by rajatm29** [comment]
limit be kept at 50. multiple callbacks would be needed, maybe we can set the offset to be an increment of 50 or 100? Need to play around a bit
