### ISSUE TITLE
Pull tracks for playlists

### ISSUE THREAD

**Issue by alexanderpepper** [alexanderpepper/spotify-utils#3]
For each playlist we pull, we'll need to pull the track details for the playlist.

This would ideally be done in the `getPlaylists()` method of `spotify-service.js` after issue #2 is complete, and would be returned in the same response.

**Comment by macacollins** [comment]
https://developer.spotify.com/web-api/get-list-users-playlists/

There's a discussion to be had here about lazy vs. eager fetching of playlists. If we do eager fetching, what if the user updates the playlist in Spotify after the initial load? I think lazy fetching might be the better fit here.

**Comment by alexanderpepper** [comment]
Closing this as it was solved by @macacollins
