### ISSUE TITLE
Play more than one track

### ISSUE THREAD

**Issue by macacollins** [alexanderpepper/spotify-utils#35]
## Current state 

The app as of writing plays only a single song, then exits. This is not ideal.

## Endpoint reference

https://developer.spotify.com/web-api/start-a-users-playback/

## Option 1: Context URI and offset

This endpoint supports a context ID (playlist or album) that we can use in combination with an offset to play a song out of our playlist list.

## Option 2: Multiple track URIs

This endpoint also takes an array of song URIs and an offset. We might have to use this to get the weighted shuffle feature.

**Comment by macacollins** [comment]
Addressed by https://github.com/alexanderpepper/spotify-utils/pull/38

**Comment by alexanderpepper** [comment]
I'll keep this one open because #38 doesn't use the offset option when passing in the array of URIs

**Comment by alexanderpepper** [comment]
Addressed by #45
